# attachment::att_amend_desc()
usethis::use_package("dplyr", min_version = TRUE)
usethis::use_package("tibble", min_version = TRUE)
usethis::use_package("htmltools", min_version = TRUE)
usethis::use_package("bslib", min_version = TRUE)
usethis::use_package("reactable", min_version = TRUE)
usethis::use_package("shinyWidgets", min_version = TRUE)
usethis::use_tidy_description()

# golem::add_js_file("script")
# golem::add_js_handler("handlers")
# golem::add_css_file("custom")
# golem::add_sass_file("custom")
usethis::use_vignette("analysePay")
devtools::build_vignettes()
# usethis::use_coverage()
# covrpage::covrpage()
# usethis::use_github()
# usethis::use_github_action()
# usethis::use_github_action_check_release()
# usethis::use_github_action_check_standard()
# usethis::use_github_action_check_full()
# usethis::use_github_action_pr_commands()
# usethis::use_travis()
# usethis::use_travis_badge()
# usethis::use_appveyor()
# usethis::use_appveyor_badge()
# usethis::use_circleci()
# usethis::use_circleci_badge()
# usethis::use_jenkins()
# usethis::use_gitlab_ci()
rstudioapi::navigateToFile("dev/03_deploy.R")
